### ISSUE TITLE
Links all dead. 

### ISSUE THREAD

**Issue by dbhurley** [andstor/verified-smart-contracts#1]
If it's hosting space related, perhaps we can identify some alternatives. This is an educational dataset.

**Comment by andstor** [comment]
Hi, the links are dead by intention. The dataset(s) are part of some papers currently in the process of publication. Once they are published, the data will be released.

**Comment by logicfool** [comment]
Sheesh I wanted them as well for a project! Any ETA when will they be available?

**Comment by minhhn2910** [comment]
Hi @andstor, any update on this ?

**Comment by andstor** [comment]
Hi @dbhurley, @logicfool, and @minhhn2910,

Our paper ([arXiv](https://arxiv.org/abs/2309.09826)) has been accepted to [ISSRE23](https://issre.github.io/2023/), so our data is now available.

**Comment by logicfool** [comment]
Thanks for the info and congratulations👌
